/**
 * generated by Xtext 2.10.0
 */
package de.tubs.cs.isf.reqeditor.administration.scoping;

import de.tubs.cs.isf.reqeditor.administration.scoping.AbstractReqAdminScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ReqAdminScopeProvider extends AbstractReqAdminScopeProvider {
}
