/*
 * generated by Xtext 2.11.0
 */
package de.tubs.cs.isf.reqeditor.dsl.serializer;

import com.google.inject.Inject;
import de.tubs.cs.isf.reqeditor.dsl.services.ReqLanguageGrammarAccess;
import de.tubs.cs.isf.requirementseditor.AND;
import de.tubs.cs.isf.requirementseditor.Attribute;
import de.tubs.cs.isf.requirementseditor.AttributeValue;
import de.tubs.cs.isf.requirementseditor.Constraint;
import de.tubs.cs.isf.requirementseditor.Literal;
import de.tubs.cs.isf.requirementseditor.NOT;
import de.tubs.cs.isf.requirementseditor.OR;
import de.tubs.cs.isf.requirementseditor.Requirement;
import de.tubs.cs.isf.requirementseditor.RequirementsEditorPackage;
import de.tubs.cs.isf.requirementseditor.RequirementsGroup;
import de.tubs.cs.isf.requirementseditor.RequirementsModel;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class ReqLanguageSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ReqLanguageGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RequirementsEditorPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RequirementsEditorPackage.AND:
				sequence_AND(context, (AND) semanticObject); 
				return; 
			case RequirementsEditorPackage.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case RequirementsEditorPackage.ATTRIBUTE_VALUE:
				sequence_AttributeValue(context, (AttributeValue) semanticObject); 
				return; 
			case RequirementsEditorPackage.CONSTRAINT:
				sequence_Constraint(context, (Constraint) semanticObject); 
				return; 
			case RequirementsEditorPackage.LITERAL:
				sequence_Literal(context, (Literal) semanticObject); 
				return; 
			case RequirementsEditorPackage.NOT:
				sequence_NOT(context, (NOT) semanticObject); 
				return; 
			case RequirementsEditorPackage.OR:
				sequence_OR(context, (OR) semanticObject); 
				return; 
			case RequirementsEditorPackage.REQUIREMENT:
				sequence_Requirement(context, (Requirement) semanticObject); 
				return; 
			case RequirementsEditorPackage.REQUIREMENTS_GROUP:
				sequence_RequirementsGroup(context, (RequirementsGroup) semanticObject); 
				return; 
			case RequirementsEditorPackage.REQUIREMENTS_MODEL:
				sequence_RequirementsModel(context, (RequirementsModel) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Expression returns AND
	 *     AND returns AND
	 *
	 * Constraint:
	 *     (operand1=Expression operand2=Expression)
	 */
	protected void sequence_AND(ISerializationContext context, AND semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RequirementsEditorPackage.Literals.NESTABLE_EXPRESSION__OPERAND1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RequirementsEditorPackage.Literals.NESTABLE_EXPRESSION__OPERAND1));
			if (transientValues.isValueTransient(semanticObject, RequirementsEditorPackage.Literals.TWO_OPERANDS_EXPRESSION__OPERAND2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RequirementsEditorPackage.Literals.TWO_OPERANDS_EXPRESSION__OPERAND2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getANDAccess().getOperand1ExpressionParserRuleCall_1_0(), semanticObject.getOperand1());
		feeder.accept(grammarAccess.getANDAccess().getOperand2ExpressionParserRuleCall_3_0(), semanticObject.getOperand2());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AttributeValue returns AttributeValue
	 *
	 * Constraint:
	 *     (value=EString? valueOf=[Attribute|EString])
	 */
	protected void sequence_AttributeValue(ISerializationContext context, AttributeValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Attribute returns Attribute
	 *
	 * Constraint:
	 *     id=EString
	 */
	protected void sequence_Attribute(ISerializationContext context, Attribute semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RequirementsEditorPackage.Literals.ATTRIBUTE__ID) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RequirementsEditorPackage.Literals.ATTRIBUTE__ID));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAttributeAccess().getIdEStringParserRuleCall_2_0(), semanticObject.getId());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Constraint returns Constraint
	 *
	 * Constraint:
	 *     (name=EString (expression+=Expression expression+=Expression*)?)
	 */
	protected void sequence_Constraint(ISerializationContext context, Constraint semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns Literal
	 *     Literal returns Literal
	 *
	 * Constraint:
	 *     element=[RequirementModelElement|EString]
	 */
	protected void sequence_Literal(ISerializationContext context, Literal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RequirementsEditorPackage.Literals.LITERAL__ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RequirementsEditorPackage.Literals.LITERAL__ELEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLiteralAccess().getElementRequirementModelElementEStringParserRuleCall_0_1(), semanticObject.eGet(RequirementsEditorPackage.Literals.LITERAL__ELEMENT, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns NOT
	 *     NOT returns NOT
	 *
	 * Constraint:
	 *     operand1=Expression
	 */
	protected void sequence_NOT(ISerializationContext context, NOT semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RequirementsEditorPackage.Literals.NESTABLE_EXPRESSION__OPERAND1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RequirementsEditorPackage.Literals.NESTABLE_EXPRESSION__OPERAND1));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNOTAccess().getOperand1ExpressionParserRuleCall_2_0(), semanticObject.getOperand1());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns OR
	 *     OR returns OR
	 *
	 * Constraint:
	 *     (operand1=Expression operand2=Expression)
	 */
	protected void sequence_OR(ISerializationContext context, OR semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RequirementsEditorPackage.Literals.NESTABLE_EXPRESSION__OPERAND1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RequirementsEditorPackage.Literals.NESTABLE_EXPRESSION__OPERAND1));
			if (transientValues.isValueTransient(semanticObject, RequirementsEditorPackage.Literals.TWO_OPERANDS_EXPRESSION__OPERAND2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RequirementsEditorPackage.Literals.TWO_OPERANDS_EXPRESSION__OPERAND2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getORAccess().getOperand1ExpressionParserRuleCall_1_0(), semanticObject.getOperand1());
		feeder.accept(grammarAccess.getORAccess().getOperand2ExpressionParserRuleCall_3_0(), semanticObject.getOperand2());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     RequirementModelElement returns Requirement
	 *     Requirement returns Requirement
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         id=EString 
	 *         description=EString? 
	 *         type=RequirementType 
	 *         priority=RequirementPriority 
	 *         (constraints+=Constraint constraints+=Constraint*)? 
	 *         (attributes+=AttributeValue attributes+=AttributeValue*)?
	 *     )
	 */
	protected void sequence_Requirement(ISerializationContext context, Requirement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     RequirementModelElement returns RequirementsGroup
	 *     RequirementsGroup returns RequirementsGroup
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         id=EString 
	 *         description=EString? 
	 *         (constraints+=Constraint constraints+=Constraint*)? 
	 *         (elements+=RequirementModelElement elements+=RequirementModelElement*)?
	 *     )
	 */
	protected void sequence_RequirementsGroup(ISerializationContext context, RequirementsGroup semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     RequirementsModel returns RequirementsModel
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         creator=EString? 
	 *         version=EString? 
	 *         (attributes+=Attribute attributes+=Attribute*)? 
	 *         (elements+=RequirementModelElement elements+=RequirementModelElement*)?
	 *     )
	 */
	protected void sequence_RequirementsModel(ISerializationContext context, RequirementsModel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
