/*
 * generated by Xtext 2.10.0
 */
package de.tubs.cs.isf.reqeditor.administration.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ReqAdminAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/tubs/cs/isf/reqeditor/administration/parser/antlr/internal/InternalReqAdmin.tokens");
	}
}
