/*
 * generated by Xtext 2.10.0
 */
package de.tubs.cs.isf.reqeditor.administration.parser.antlr;

import com.google.inject.Inject;
import de.tubs.cs.isf.reqeditor.administration.parser.antlr.internal.InternalReqAdminParser;
import de.tubs.cs.isf.reqeditor.administration.services.ReqAdminGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ReqAdminParser extends AbstractAntlrParser {

	@Inject
	private ReqAdminGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalReqAdminParser createParser(XtextTokenStream stream) {
		return new InternalReqAdminParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RequirementsModel";
	}

	public ReqAdminGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReqAdminGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
