/**
 * generated by Xtext 2.10.0
 */
package de.tubs.cs.isf.reqeditor.administration;

import de.tubs.cs.isf.reqeditor.administration.AbstractReqAdminRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReqAdminRuntimeModule extends AbstractReqAdminRuntimeModule {
}
