/**
 * generated by Xtext 2.10.0
 */
package de.tubs.cs.isf.reqeditor.administration;

import de.tubs.cs.isf.reqeditor.administration.ReqAdminStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReqAdminStandaloneSetup extends ReqAdminStandaloneSetupGenerated {
  public static void doSetup() {
    ReqAdminStandaloneSetup _reqAdminStandaloneSetup = new ReqAdminStandaloneSetup();
    _reqAdminStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
