/*
 * generated by Xtext 2.10.0
 */
package de.tubs.cs.isf.reqeditor.administration


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ReqAdminStandaloneSetup extends ReqAdminStandaloneSetupGenerated {

	def static void doSetup() {
		new ReqAdminStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
