/*
 * generated by Xtext 2.10.0
 */
package de.tubs.cs.isf.reqeditor.administration


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ReqAdminRuntimeModule extends AbstractReqAdminRuntimeModule {
}
