/**
 * generated by Xtext 2.10.0
 */
package de.tubs.cs.isf.reqeditor.administration.ui;

import de.tubs.cs.isf.reqeditor.administration.ui.AbstractReqAdminUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ReqAdminUiModule extends AbstractReqAdminUiModule {
  public ReqAdminUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
