/*
 * generated by Xtext 2.11.0
 */
package de.tubs.cs.isf.reqeditor.dsl.parser.antlr;

import com.google.inject.Inject;
import de.tubs.cs.isf.reqeditor.dsl.parser.antlr.internal.InternalReqLanguageParser;
import de.tubs.cs.isf.reqeditor.dsl.services.ReqLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ReqLanguageParser extends AbstractAntlrParser {

	@Inject
	private ReqLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalReqLanguageParser createParser(XtextTokenStream stream) {
		return new InternalReqLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RequirementsModel";
	}

	public ReqLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReqLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
