/*
 * generated by Xtext 2.11.0
 */
package de.tubs.cs.isf.reqeditor.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ReqLanguageStandaloneSetup extends ReqLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new ReqLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
