/*
 * generated by Xtext 2.11.0
 */
package de.tubs.cs.isf.reqeditor.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ReqLanguageRuntimeModule extends AbstractReqLanguageRuntimeModule {
}
