/*
 * generated by Xtext 2.11.0
 */
package de.tubs.cs.isf.reqeditor.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ReqLanguageGrammarAccess extends AbstractGrammarElementFinder {
	
	public class RequirementsModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.RequirementsModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRequirementsModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNewKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRequirementsModelKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCreatedKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cByKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cCreatorAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cCreatorEStringParserRuleCall_4_2_0 = (RuleCall)cCreatorAssignment_4_2.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cVersionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cVersionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cVersionEStringParserRuleCall_5_1_0 = (RuleCall)cVersionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cElementsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cElementsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cElementsRequirementModelElementParserRuleCall_6_2_0 = (RuleCall)cElementsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cElementsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cElementsRequirementModelElementParserRuleCall_6_3_1_0 = (RuleCall)cElementsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAttributesKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cAttributesAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cAttributesAttributeParserRuleCall_7_2_0 = (RuleCall)cAttributesAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cAttributesAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cAttributesAttributeParserRuleCall_7_3_1_0 = (RuleCall)cAttributesAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		
		//RequirementsModel:
		//	{RequirementsModel}
		//	'new' 'RequirementsModel'
		//	name=EString ('created' 'by' creator=EString)? ('version' version=EString)? ('elements' '{'
		//	elements+=RequirementModelElement ("," elements+=RequirementModelElement)* '}')? ('attributes' '{'
		//	attributes+=Attribute ("," attributes+=Attribute)* '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{RequirementsModel} 'new' 'RequirementsModel' name=EString ('created' 'by' creator=EString)? ('version'
		//version=EString)? ('elements' '{' elements+=RequirementModelElement ("," elements+=RequirementModelElement)* '}')?
		//('attributes' '{' attributes+=Attribute ("," attributes+=Attribute)* '}')?
		public Group getGroup() { return cGroup; }
		
		//{RequirementsModel}
		public Action getRequirementsModelAction_0() { return cRequirementsModelAction_0; }
		
		//'new'
		public Keyword getNewKeyword_1() { return cNewKeyword_1; }
		
		//'RequirementsModel'
		public Keyword getRequirementsModelKeyword_2() { return cRequirementsModelKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//('created' 'by' creator=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'created'
		public Keyword getCreatedKeyword_4_0() { return cCreatedKeyword_4_0; }
		
		//'by'
		public Keyword getByKeyword_4_1() { return cByKeyword_4_1; }
		
		//creator=EString
		public Assignment getCreatorAssignment_4_2() { return cCreatorAssignment_4_2; }
		
		//EString
		public RuleCall getCreatorEStringParserRuleCall_4_2_0() { return cCreatorEStringParserRuleCall_4_2_0; }
		
		//('version' version=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'version'
		public Keyword getVersionKeyword_5_0() { return cVersionKeyword_5_0; }
		
		//version=EString
		public Assignment getVersionAssignment_5_1() { return cVersionAssignment_5_1; }
		
		//EString
		public RuleCall getVersionEStringParserRuleCall_5_1_0() { return cVersionEStringParserRuleCall_5_1_0; }
		
		//('elements' '{' elements+=RequirementModelElement ("," elements+=RequirementModelElement)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'elements'
		public Keyword getElementsKeyword_6_0() { return cElementsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//elements+=RequirementModelElement
		public Assignment getElementsAssignment_6_2() { return cElementsAssignment_6_2; }
		
		//RequirementModelElement
		public RuleCall getElementsRequirementModelElementParserRuleCall_6_2_0() { return cElementsRequirementModelElementParserRuleCall_6_2_0; }
		
		//("," elements+=RequirementModelElement)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//elements+=RequirementModelElement
		public Assignment getElementsAssignment_6_3_1() { return cElementsAssignment_6_3_1; }
		
		//RequirementModelElement
		public RuleCall getElementsRequirementModelElementParserRuleCall_6_3_1_0() { return cElementsRequirementModelElementParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('attributes' '{' attributes+=Attribute ("," attributes+=Attribute)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'attributes'
		public Keyword getAttributesKeyword_7_0() { return cAttributesKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//attributes+=Attribute
		public Assignment getAttributesAssignment_7_2() { return cAttributesAssignment_7_2; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_7_2_0() { return cAttributesAttributeParserRuleCall_7_2_0; }
		
		//("," attributes+=Attribute)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//attributes+=Attribute
		public Assignment getAttributesAssignment_7_3_1() { return cAttributesAssignment_7_3_1; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_7_3_1_0() { return cAttributesAttributeParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
	}
	public class RequirementModelElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.RequirementModelElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRequirementsGroupParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRequirementParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//RequirementModelElement:
		//	RequirementsGroup | Requirement;
		@Override public ParserRule getRule() { return rule; }
		
		//RequirementsGroup | Requirement
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//RequirementsGroup
		public RuleCall getRequirementsGroupParserRuleCall_0() { return cRequirementsGroupParserRuleCall_0; }
		
		//Requirement
		public RuleCall getRequirementParserRuleCall_1() { return cRequirementParserRuleCall_1; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cORParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cANDParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNOTParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cLiteralParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Expression:
		//	OR | AND | NOT | Literal;
		@Override public ParserRule getRule() { return rule; }
		
		//OR | AND | NOT | Literal
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//OR
		public RuleCall getORParserRuleCall_0() { return cORParserRuleCall_0; }
		
		//AND
		public RuleCall getANDParserRuleCall_1() { return cANDParserRuleCall_1; }
		
		//NOT
		public RuleCall getNOTParserRuleCall_2() { return cNOTParserRuleCall_2; }
		
		//Literal
		public RuleCall getLiteralParserRuleCall_3() { return cLiteralParserRuleCall_3; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAttributeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNewKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAttributeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIdKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIdAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_3_1_0 = (RuleCall)cIdAssignment_3_1.eContents().get(0);
		
		//Attribute:
		//	{Attribute}
		//	'new' 'Attribute' ('id' id=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Attribute} 'new' 'Attribute' ('id' id=EString)?
		public Group getGroup() { return cGroup; }
		
		//{Attribute}
		public Action getAttributeAction_0() { return cAttributeAction_0; }
		
		//'new'
		public Keyword getNewKeyword_1() { return cNewKeyword_1; }
		
		//'Attribute'
		public Keyword getAttributeKeyword_2() { return cAttributeKeyword_2; }
		
		//('id' id=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'id'
		public Keyword getIdKeyword_3_0() { return cIdKeyword_3_0; }
		
		//id=EString
		public Assignment getIdAssignment_3_1() { return cIdAssignment_3_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_3_1_0() { return cIdEStringParserRuleCall_3_1_0; }
	}
	public class ConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.Constraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConstraintAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNewKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cConstraintKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cExpressionAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cExpressionExpressionParserRuleCall_4_0_0 = (RuleCall)cExpressionAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cExpressionAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cExpressionExpressionParserRuleCall_4_1_1_0 = (RuleCall)cExpressionAssignment_4_1_1.eContents().get(0);
		
		//Constraint:
		//	{Constraint}
		//	'new' 'Constraint'
		//	name=EString (expression+=Expression ("," expression+=Expression)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Constraint} 'new' 'Constraint' name=EString (expression+=Expression ("," expression+=Expression)*)?
		public Group getGroup() { return cGroup; }
		
		//{Constraint}
		public Action getConstraintAction_0() { return cConstraintAction_0; }
		
		//'new'
		public Keyword getNewKeyword_1() { return cNewKeyword_1; }
		
		//'Constraint'
		public Keyword getConstraintKeyword_2() { return cConstraintKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//(expression+=Expression ("," expression+=Expression)*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//expression+=Expression
		public Assignment getExpressionAssignment_4_0() { return cExpressionAssignment_4_0; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_4_0_0() { return cExpressionExpressionParserRuleCall_4_0_0; }
		
		//("," expression+=Expression)*
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//","
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }
		
		//expression+=Expression
		public Assignment getExpressionAssignment_4_1_1() { return cExpressionAssignment_4_1_1; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_4_1_1_0() { return cExpressionExpressionParserRuleCall_4_1_1_0; }
	}
	public class RequirementsGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.RequirementsGroup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRequirementsGroupAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNewKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRequirementsGroupKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIdKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cIdAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_4_1_0 = (RuleCall)cIdAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cConstraintsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cConstraintsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cConstraintsConstraintParserRuleCall_6_2_0 = (RuleCall)cConstraintsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cConstraintsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cConstraintsConstraintParserRuleCall_6_3_1_0 = (RuleCall)cConstraintsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cElementsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cElementsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cElementsRequirementModelElementParserRuleCall_7_2_0 = (RuleCall)cElementsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cElementsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cElementsRequirementModelElementParserRuleCall_7_3_1_0 = (RuleCall)cElementsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		
		//RequirementsGroup:
		//	{RequirementsGroup}
		//	'new' 'RequirementsGroup'
		//	name=EString ('id' id=EString)? ('description' description=EString)? ('constraints' '{' constraints+=Constraint (","
		//	constraints+=Constraint)* '}')? ('elements' '{' elements+=RequirementModelElement (","
		//	elements+=RequirementModelElement)* '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{RequirementsGroup} 'new' 'RequirementsGroup' name=EString ('id' id=EString)? ('description' description=EString)?
		//('constraints' '{' constraints+=Constraint ("," constraints+=Constraint)* '}')? ('elements' '{'
		//elements+=RequirementModelElement ("," elements+=RequirementModelElement)* '}')?
		public Group getGroup() { return cGroup; }
		
		//{RequirementsGroup}
		public Action getRequirementsGroupAction_0() { return cRequirementsGroupAction_0; }
		
		//'new'
		public Keyword getNewKeyword_1() { return cNewKeyword_1; }
		
		//'RequirementsGroup'
		public Keyword getRequirementsGroupKeyword_2() { return cRequirementsGroupKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//('id' id=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'id'
		public Keyword getIdKeyword_4_0() { return cIdKeyword_4_0; }
		
		//id=EString
		public Assignment getIdAssignment_4_1() { return cIdAssignment_4_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_4_1_0() { return cIdEStringParserRuleCall_4_1_0; }
		
		//('description' description=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'description'
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_5_1_0() { return cDescriptionEStringParserRuleCall_5_1_0; }
		
		//('constraints' '{' constraints+=Constraint ("," constraints+=Constraint)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'constraints'
		public Keyword getConstraintsKeyword_6_0() { return cConstraintsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//constraints+=Constraint
		public Assignment getConstraintsAssignment_6_2() { return cConstraintsAssignment_6_2; }
		
		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_6_2_0() { return cConstraintsConstraintParserRuleCall_6_2_0; }
		
		//("," constraints+=Constraint)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//constraints+=Constraint
		public Assignment getConstraintsAssignment_6_3_1() { return cConstraintsAssignment_6_3_1; }
		
		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_6_3_1_0() { return cConstraintsConstraintParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('elements' '{' elements+=RequirementModelElement ("," elements+=RequirementModelElement)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'elements'
		public Keyword getElementsKeyword_7_0() { return cElementsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//elements+=RequirementModelElement
		public Assignment getElementsAssignment_7_2() { return cElementsAssignment_7_2; }
		
		//RequirementModelElement
		public RuleCall getElementsRequirementModelElementParserRuleCall_7_2_0() { return cElementsRequirementModelElementParserRuleCall_7_2_0; }
		
		//("," elements+=RequirementModelElement)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//elements+=RequirementModelElement
		public Assignment getElementsAssignment_7_3_1() { return cElementsAssignment_7_3_1; }
		
		//RequirementModelElement
		public RuleCall getElementsRequirementModelElementParserRuleCall_7_3_1_0() { return cElementsRequirementModelElementParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
	}
	public class RequirementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.Requirement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRequirementAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNewKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRequirementKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIdKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cIdAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_4_1_0 = (RuleCall)cIdAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTypeRequirementTypeEnumRuleCall_6_1_0 = (RuleCall)cTypeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPriorityKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPriorityAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPriorityRequirementPriorityEnumRuleCall_7_1_0 = (RuleCall)cPriorityAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cConstraintsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cConstraintsAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cConstraintsConstraintParserRuleCall_8_2_0 = (RuleCall)cConstraintsAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cConstraintsAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cConstraintsConstraintParserRuleCall_8_3_1_0 = (RuleCall)cConstraintsAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cAttributesKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cAttributesAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cAttributesAttributeValueParserRuleCall_9_2_0 = (RuleCall)cAttributesAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cAttributesAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cAttributesAttributeValueParserRuleCall_9_3_1_0 = (RuleCall)cAttributesAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		
		//Requirement:
		//	{Requirement}
		//	'new' 'Requirement'
		//	name=EString ('id' id=EString)? ('description' description=EString)? ('type' type=RequirementType)? ('priority'
		//	priority=RequirementPriority)? ('constraints' '{' constraints+=Constraint ("," constraints+=Constraint)* '}')?
		//	('attributes' '{' attributes+=AttributeValue ("," attributes+=AttributeValue)* '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Requirement} 'new' 'Requirement' name=EString ('id' id=EString)? ('description' description=EString)? ('type'
		//type=RequirementType)? ('priority' priority=RequirementPriority)? ('constraints' '{' constraints+=Constraint (","
		//constraints+=Constraint)* '}')? ('attributes' '{' attributes+=AttributeValue ("," attributes+=AttributeValue)* '}')?
		public Group getGroup() { return cGroup; }
		
		//{Requirement}
		public Action getRequirementAction_0() { return cRequirementAction_0; }
		
		//'new'
		public Keyword getNewKeyword_1() { return cNewKeyword_1; }
		
		//'Requirement'
		public Keyword getRequirementKeyword_2() { return cRequirementKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//('id' id=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'id'
		public Keyword getIdKeyword_4_0() { return cIdKeyword_4_0; }
		
		//id=EString
		public Assignment getIdAssignment_4_1() { return cIdAssignment_4_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_4_1_0() { return cIdEStringParserRuleCall_4_1_0; }
		
		//('description' description=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'description'
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_5_1_0() { return cDescriptionEStringParserRuleCall_5_1_0; }
		
		//('type' type=RequirementType)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'type'
		public Keyword getTypeKeyword_6_0() { return cTypeKeyword_6_0; }
		
		//type=RequirementType
		public Assignment getTypeAssignment_6_1() { return cTypeAssignment_6_1; }
		
		//RequirementType
		public RuleCall getTypeRequirementTypeEnumRuleCall_6_1_0() { return cTypeRequirementTypeEnumRuleCall_6_1_0; }
		
		//('priority' priority=RequirementPriority)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'priority'
		public Keyword getPriorityKeyword_7_0() { return cPriorityKeyword_7_0; }
		
		//priority=RequirementPriority
		public Assignment getPriorityAssignment_7_1() { return cPriorityAssignment_7_1; }
		
		//RequirementPriority
		public RuleCall getPriorityRequirementPriorityEnumRuleCall_7_1_0() { return cPriorityRequirementPriorityEnumRuleCall_7_1_0; }
		
		//('constraints' '{' constraints+=Constraint ("," constraints+=Constraint)* '}')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'constraints'
		public Keyword getConstraintsKeyword_8_0() { return cConstraintsKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//constraints+=Constraint
		public Assignment getConstraintsAssignment_8_2() { return cConstraintsAssignment_8_2; }
		
		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_8_2_0() { return cConstraintsConstraintParserRuleCall_8_2_0; }
		
		//("," constraints+=Constraint)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//constraints+=Constraint
		public Assignment getConstraintsAssignment_8_3_1() { return cConstraintsAssignment_8_3_1; }
		
		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_8_3_1_0() { return cConstraintsConstraintParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//('attributes' '{' attributes+=AttributeValue ("," attributes+=AttributeValue)* '}')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'attributes'
		public Keyword getAttributesKeyword_9_0() { return cAttributesKeyword_9_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }
		
		//attributes+=AttributeValue
		public Assignment getAttributesAssignment_9_2() { return cAttributesAssignment_9_2; }
		
		//AttributeValue
		public RuleCall getAttributesAttributeValueParserRuleCall_9_2_0() { return cAttributesAttributeValueParserRuleCall_9_2_0; }
		
		//("," attributes+=AttributeValue)*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//attributes+=AttributeValue
		public Assignment getAttributesAssignment_9_3_1() { return cAttributesAssignment_9_3_1; }
		
		//AttributeValue
		public RuleCall getAttributesAttributeValueParserRuleCall_9_3_1_0() { return cAttributesAttributeValueParserRuleCall_9_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }
	}
	public class ORElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.OR");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOperand1Assignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOperand1ExpressionParserRuleCall_1_0 = (RuleCall)cOperand1Assignment_1.eContents().get(0);
		private final Keyword cORKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOperand2Assignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperand2ExpressionParserRuleCall_3_0 = (RuleCall)cOperand2Assignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//OR:
		//	'('
		//	operand1=Expression
		//	'OR'
		//	operand2=Expression
		//	')';
		@Override public ParserRule getRule() { return rule; }
		
		//'(' operand1=Expression 'OR' operand2=Expression ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//operand1=Expression
		public Assignment getOperand1Assignment_1() { return cOperand1Assignment_1; }
		
		//Expression
		public RuleCall getOperand1ExpressionParserRuleCall_1_0() { return cOperand1ExpressionParserRuleCall_1_0; }
		
		//'OR'
		public Keyword getORKeyword_2() { return cORKeyword_2; }
		
		//operand2=Expression
		public Assignment getOperand2Assignment_3() { return cOperand2Assignment_3; }
		
		//Expression
		public RuleCall getOperand2ExpressionParserRuleCall_3_0() { return cOperand2ExpressionParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ANDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.AND");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOperand1Assignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOperand1ExpressionParserRuleCall_1_0 = (RuleCall)cOperand1Assignment_1.eContents().get(0);
		private final Keyword cANDKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOperand2Assignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperand2ExpressionParserRuleCall_3_0 = (RuleCall)cOperand2Assignment_3.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//AND:
		//	'['
		//	operand1=Expression
		//	'AND'
		//	operand2=Expression
		//	']';
		@Override public ParserRule getRule() { return rule; }
		
		//'[' operand1=Expression 'AND' operand2=Expression ']'
		public Group getGroup() { return cGroup; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }
		
		//operand1=Expression
		public Assignment getOperand1Assignment_1() { return cOperand1Assignment_1; }
		
		//Expression
		public RuleCall getOperand1ExpressionParserRuleCall_1_0() { return cOperand1ExpressionParserRuleCall_1_0; }
		
		//'AND'
		public Keyword getANDKeyword_2() { return cANDKeyword_2; }
		
		//operand2=Expression
		public Assignment getOperand2Assignment_3() { return cOperand2Assignment_3; }
		
		//Expression
		public RuleCall getOperand2ExpressionParserRuleCall_3_0() { return cOperand2ExpressionParserRuleCall_3_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }
	}
	public class NOTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.NOT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNOTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOperand1Keyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOperand1Assignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperand1ExpressionParserRuleCall_3_0 = (RuleCall)cOperand1Assignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//NOT:
		//	'NOT' '('
		//	'operand1' operand1=Expression
		//	')';
		@Override public ParserRule getRule() { return rule; }
		
		//'NOT' '(' 'operand1' operand1=Expression ')'
		public Group getGroup() { return cGroup; }
		
		//'NOT'
		public Keyword getNOTKeyword_0() { return cNOTKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//'operand1'
		public Keyword getOperand1Keyword_2() { return cOperand1Keyword_2; }
		
		//operand1=Expression
		public Assignment getOperand1Assignment_3() { return cOperand1Assignment_3; }
		
		//Expression
		public RuleCall getOperand1ExpressionParserRuleCall_3_0() { return cOperand1ExpressionParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class LiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.Literal");
		private final Assignment cElementAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cElementRequirementModelElementCrossReference_0 = (CrossReference)cElementAssignment.eContents().get(0);
		private final RuleCall cElementRequirementModelElementEStringParserRuleCall_0_1 = (RuleCall)cElementRequirementModelElementCrossReference_0.eContents().get(1);
		
		//Literal:
		//	element=[RequirementModelElement|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//element=[RequirementModelElement|EString]
		public Assignment getElementAssignment() { return cElementAssignment; }
		
		//[RequirementModelElement|EString]
		public CrossReference getElementRequirementModelElementCrossReference_0() { return cElementRequirementModelElementCrossReference_0; }
		
		//EString
		public RuleCall getElementRequirementModelElementEStringParserRuleCall_0_1() { return cElementRequirementModelElementEStringParserRuleCall_0_1; }
	}
	public class AttributeValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.AttributeValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAttributeValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNewKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAttributeValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValueOfKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cValueOfAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cValueOfAttributeCrossReference_4_1_0 = (CrossReference)cValueOfAssignment_4_1.eContents().get(0);
		private final RuleCall cValueOfAttributeEStringParserRuleCall_4_1_0_1 = (RuleCall)cValueOfAttributeCrossReference_4_1_0.eContents().get(1);
		
		//AttributeValue:
		//	{AttributeValue}
		//	'new' 'AttributeValue' ('value' value=EString)? ('valueOf' valueOf=[Attribute|EString])?;
		@Override public ParserRule getRule() { return rule; }
		
		//{AttributeValue} 'new' 'AttributeValue' ('value' value=EString)? ('valueOf' valueOf=[Attribute|EString])?
		public Group getGroup() { return cGroup; }
		
		//{AttributeValue}
		public Action getAttributeValueAction_0() { return cAttributeValueAction_0; }
		
		//'new'
		public Keyword getNewKeyword_1() { return cNewKeyword_1; }
		
		//'AttributeValue'
		public Keyword getAttributeValueKeyword_2() { return cAttributeValueKeyword_2; }
		
		//('value' value=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'value'
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }
		
		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }
		
		//('valueOf' valueOf=[Attribute|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'valueOf'
		public Keyword getValueOfKeyword_4_0() { return cValueOfKeyword_4_0; }
		
		//valueOf=[Attribute|EString]
		public Assignment getValueOfAssignment_4_1() { return cValueOfAssignment_4_1; }
		
		//[Attribute|EString]
		public CrossReference getValueOfAttributeCrossReference_4_1_0() { return cValueOfAttributeCrossReference_4_1_0; }
		
		//EString
		public RuleCall getValueOfAttributeEStringParserRuleCall_4_1_0_1() { return cValueOfAttributeEStringParserRuleCall_4_1_0_1; }
	}
	
	public class RequirementTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.RequirementType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFUNCTIONALEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFUNCTIONALFUNCTIONALKeyword_0_0 = (Keyword)cFUNCTIONALEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNON_FUNCTIONALEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNON_FUNCTIONALNON_FUNCTIONALKeyword_1_0 = (Keyword)cNON_FUNCTIONALEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNONEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNONENONEKeyword_2_0 = (Keyword)cNONEEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cOTHEREnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cOTHEROTHERKeyword_3_0 = (Keyword)cOTHEREnumLiteralDeclaration_3.eContents().get(0);
		
		//enum RequirementType:
		//	FUNCTIONAL | NON_FUNCTIONAL | NONE | OTHER;
		public EnumRule getRule() { return rule; }
		
		//FUNCTIONAL | NON_FUNCTIONAL | NONE | OTHER
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FUNCTIONAL
		public EnumLiteralDeclaration getFUNCTIONALEnumLiteralDeclaration_0() { return cFUNCTIONALEnumLiteralDeclaration_0; }
		
		//'FUNCTIONAL'
		public Keyword getFUNCTIONALFUNCTIONALKeyword_0_0() { return cFUNCTIONALFUNCTIONALKeyword_0_0; }
		
		//NON_FUNCTIONAL
		public EnumLiteralDeclaration getNON_FUNCTIONALEnumLiteralDeclaration_1() { return cNON_FUNCTIONALEnumLiteralDeclaration_1; }
		
		//'NON_FUNCTIONAL'
		public Keyword getNON_FUNCTIONALNON_FUNCTIONALKeyword_1_0() { return cNON_FUNCTIONALNON_FUNCTIONALKeyword_1_0; }
		
		//NONE
		public EnumLiteralDeclaration getNONEEnumLiteralDeclaration_2() { return cNONEEnumLiteralDeclaration_2; }
		
		//'NONE'
		public Keyword getNONENONEKeyword_2_0() { return cNONENONEKeyword_2_0; }
		
		//OTHER
		public EnumLiteralDeclaration getOTHEREnumLiteralDeclaration_3() { return cOTHEREnumLiteralDeclaration_3; }
		
		//'OTHER'
		public Keyword getOTHEROTHERKeyword_3_0() { return cOTHEROTHERKeyword_3_0; }
	}
	public class RequirementPriorityElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "de.tubs.cs.isf.reqeditor.dsl.ReqLanguage.RequirementPriority");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cESSENTIALEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cESSENTIALESSENTIALKeyword_0_0 = (Keyword)cESSENTIALEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCONDITIONALEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCONDITIONALCONDITIONALKeyword_1_0 = (Keyword)cCONDITIONALEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cOPTIONALEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cOPTIONALOPTIONALKeyword_2_0 = (Keyword)cOPTIONALEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum RequirementPriority:
		//	ESSENTIAL | CONDITIONAL | OPTIONAL;
		public EnumRule getRule() { return rule; }
		
		//ESSENTIAL | CONDITIONAL | OPTIONAL
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ESSENTIAL
		public EnumLiteralDeclaration getESSENTIALEnumLiteralDeclaration_0() { return cESSENTIALEnumLiteralDeclaration_0; }
		
		//'ESSENTIAL'
		public Keyword getESSENTIALESSENTIALKeyword_0_0() { return cESSENTIALESSENTIALKeyword_0_0; }
		
		//CONDITIONAL
		public EnumLiteralDeclaration getCONDITIONALEnumLiteralDeclaration_1() { return cCONDITIONALEnumLiteralDeclaration_1; }
		
		//'CONDITIONAL'
		public Keyword getCONDITIONALCONDITIONALKeyword_1_0() { return cCONDITIONALCONDITIONALKeyword_1_0; }
		
		//OPTIONAL
		public EnumLiteralDeclaration getOPTIONALEnumLiteralDeclaration_2() { return cOPTIONALEnumLiteralDeclaration_2; }
		
		//'OPTIONAL'
		public Keyword getOPTIONALOPTIONALKeyword_2_0() { return cOPTIONALOPTIONALKeyword_2_0; }
	}
	
	private final RequirementsModelElements pRequirementsModel;
	private final RequirementModelElementElements pRequirementModelElement;
	private final ExpressionElements pExpression;
	private final EStringElements pEString;
	private final AttributeElements pAttribute;
	private final ConstraintElements pConstraint;
	private final RequirementsGroupElements pRequirementsGroup;
	private final RequirementElements pRequirement;
	private final ORElements pOR;
	private final ANDElements pAND;
	private final NOTElements pNOT;
	private final LiteralElements pLiteral;
	private final RequirementTypeElements eRequirementType;
	private final RequirementPriorityElements eRequirementPriority;
	private final AttributeValueElements pAttributeValue;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ReqLanguageGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRequirementsModel = new RequirementsModelElements();
		this.pRequirementModelElement = new RequirementModelElementElements();
		this.pExpression = new ExpressionElements();
		this.pEString = new EStringElements();
		this.pAttribute = new AttributeElements();
		this.pConstraint = new ConstraintElements();
		this.pRequirementsGroup = new RequirementsGroupElements();
		this.pRequirement = new RequirementElements();
		this.pOR = new ORElements();
		this.pAND = new ANDElements();
		this.pNOT = new NOTElements();
		this.pLiteral = new LiteralElements();
		this.eRequirementType = new RequirementTypeElements();
		this.eRequirementPriority = new RequirementPriorityElements();
		this.pAttributeValue = new AttributeValueElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.tubs.cs.isf.reqeditor.dsl.ReqLanguage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RequirementsModel:
	//	{RequirementsModel}
	//	'new' 'RequirementsModel'
	//	name=EString ('created' 'by' creator=EString)? ('version' version=EString)? ('elements' '{'
	//	elements+=RequirementModelElement ("," elements+=RequirementModelElement)* '}')? ('attributes' '{'
	//	attributes+=Attribute ("," attributes+=Attribute)* '}')?;
	public RequirementsModelElements getRequirementsModelAccess() {
		return pRequirementsModel;
	}
	
	public ParserRule getRequirementsModelRule() {
		return getRequirementsModelAccess().getRule();
	}
	
	//RequirementModelElement:
	//	RequirementsGroup | Requirement;
	public RequirementModelElementElements getRequirementModelElementAccess() {
		return pRequirementModelElement;
	}
	
	public ParserRule getRequirementModelElementRule() {
		return getRequirementModelElementAccess().getRule();
	}
	
	//Expression:
	//	OR | AND | NOT | Literal;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Attribute:
	//	{Attribute}
	//	'new' 'Attribute' ('id' id=EString)?;
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//Constraint:
	//	{Constraint}
	//	'new' 'Constraint'
	//	name=EString (expression+=Expression ("," expression+=Expression)*)?;
	public ConstraintElements getConstraintAccess() {
		return pConstraint;
	}
	
	public ParserRule getConstraintRule() {
		return getConstraintAccess().getRule();
	}
	
	//RequirementsGroup:
	//	{RequirementsGroup}
	//	'new' 'RequirementsGroup'
	//	name=EString ('id' id=EString)? ('description' description=EString)? ('constraints' '{' constraints+=Constraint (","
	//	constraints+=Constraint)* '}')? ('elements' '{' elements+=RequirementModelElement (","
	//	elements+=RequirementModelElement)* '}')?;
	public RequirementsGroupElements getRequirementsGroupAccess() {
		return pRequirementsGroup;
	}
	
	public ParserRule getRequirementsGroupRule() {
		return getRequirementsGroupAccess().getRule();
	}
	
	//Requirement:
	//	{Requirement}
	//	'new' 'Requirement'
	//	name=EString ('id' id=EString)? ('description' description=EString)? ('type' type=RequirementType)? ('priority'
	//	priority=RequirementPriority)? ('constraints' '{' constraints+=Constraint ("," constraints+=Constraint)* '}')?
	//	('attributes' '{' attributes+=AttributeValue ("," attributes+=AttributeValue)* '}')?;
	public RequirementElements getRequirementAccess() {
		return pRequirement;
	}
	
	public ParserRule getRequirementRule() {
		return getRequirementAccess().getRule();
	}
	
	//OR:
	//	'('
	//	operand1=Expression
	//	'OR'
	//	operand2=Expression
	//	')';
	public ORElements getORAccess() {
		return pOR;
	}
	
	public ParserRule getORRule() {
		return getORAccess().getRule();
	}
	
	//AND:
	//	'['
	//	operand1=Expression
	//	'AND'
	//	operand2=Expression
	//	']';
	public ANDElements getANDAccess() {
		return pAND;
	}
	
	public ParserRule getANDRule() {
		return getANDAccess().getRule();
	}
	
	//NOT:
	//	'NOT' '('
	//	'operand1' operand1=Expression
	//	')';
	public NOTElements getNOTAccess() {
		return pNOT;
	}
	
	public ParserRule getNOTRule() {
		return getNOTAccess().getRule();
	}
	
	//Literal:
	//	element=[RequirementModelElement|EString];
	public LiteralElements getLiteralAccess() {
		return pLiteral;
	}
	
	public ParserRule getLiteralRule() {
		return getLiteralAccess().getRule();
	}
	
	//enum RequirementType:
	//	FUNCTIONAL | NON_FUNCTIONAL | NONE | OTHER;
	public RequirementTypeElements getRequirementTypeAccess() {
		return eRequirementType;
	}
	
	public EnumRule getRequirementTypeRule() {
		return getRequirementTypeAccess().getRule();
	}
	
	//enum RequirementPriority:
	//	ESSENTIAL | CONDITIONAL | OPTIONAL;
	public RequirementPriorityElements getRequirementPriorityAccess() {
		return eRequirementPriority;
	}
	
	public EnumRule getRequirementPriorityRule() {
		return getRequirementPriorityAccess().getRule();
	}
	
	//AttributeValue:
	//	{AttributeValue}
	//	'new' 'AttributeValue' ('value' value=EString)? ('valueOf' valueOf=[Attribute|EString])?;
	public AttributeValueElements getAttributeValueAccess() {
		return pAttributeValue;
	}
	
	public ParserRule getAttributeValueRule() {
		return getAttributeValueAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
