/**
 * generated by Xtext 2.11.0
 */
package de.tubs.cs.isf.reqeditor.dsl;

import de.tubs.cs.isf.reqeditor.dsl.AbstractReqLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReqLanguageRuntimeModule extends AbstractReqLanguageRuntimeModule {
}
