/**
 * generated by Xtext 2.11.0
 */
package de.tubs.cs.isf.reqeditor.dsl;

import de.tubs.cs.isf.reqeditor.dsl.ReqLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReqLanguageStandaloneSetup extends ReqLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new ReqLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
