/**
 * generated by Xtext 2.10.0
 */
package de.tubs.cs.isf.reqeditor.administration.validation;

import de.tubs.cs.isf.reqeditor.administration.validation.AbstractReqAdminValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ReqAdminValidator extends AbstractReqAdminValidator {
}
