/**
 * generated by Xtext 2.11.0
 */
package de.tubs.cs.isf.reqeditor.dsl.tests;

import com.google.inject.Inject;
import de.tubs.cs.isf.reqeditor.dsl.tests.ReqLanguageInjectorProvider;
import de.tubs.cs.isf.requirementseditor.RequirementsModel;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(ReqLanguageInjectorProvider.class)
@SuppressWarnings("all")
public class ReqLanguageParsingTest {
  @Inject
  private ParseHelper<RequirementsModel> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final RequirementsModel result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
