/*
 * generated by Xtext 2.10.0
 */
package de.tubs.cs.isf.reqeditor.administration.ui;

import com.google.inject.Injector;
import de.tubs.cs.isf.reqeditor.administration.ui.internal.AdministrationActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ReqAdminExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AdministrationActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AdministrationActivator.getInstance().getInjector(AdministrationActivator.DE_TUBS_CS_ISF_REQEDITOR_ADMINISTRATION_REQADMIN);
	}
	
}
