/**
 * generated by Xtext 2.10.0
 */
package de.tubs.cs.isf.reqeditor.administration.tests;

import com.google.inject.Inject;
import de.tubs.cs.isf.reqeditor.administration.tests.ReqAdminInjectorProvider;
import de.tubs.cs.isf.requirementseditor.RequirementsModel;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(ReqAdminInjectorProvider.class)
@SuppressWarnings("all")
public class ReqAdminParsingTest {
  @Inject
  private ParseHelper<RequirementsModel> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final RequirementsModel result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
