/**
 * generated by Xtext 2.11.0
 */
package de.tubs.cs.isf.reqeditor.dsl.validation;

import de.tubs.cs.isf.reqeditor.dsl.validation.AbstractReqLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ReqLanguageValidator extends AbstractReqLanguageValidator {
}
