/**
 * generated by Xtext 2.11.0
 */
package de.tubs.cs.isf.reqeditor.dsl.scoping;

import de.tubs.cs.isf.reqeditor.dsl.scoping.AbstractReqLanguageScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ReqLanguageScopeProvider extends AbstractReqLanguageScopeProvider {
}
